import type { Metadata } from 'next';
import '../styles/globals.scss';
import { Golos } from './fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <Header /> */}
      <body className={Golos.className}>{children}</body>
    </html>
  );
}
